### ISSUE TITLE
[Bug] 开发环境下，form渲染组件，控制台有 formMode warning提示，比较影响日志调试

### ISSUE THREAD

**Issue by Henry129999** [jd-opensource/drip-form#237] opened 2022-08-05 03:30 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/JDFED/drip-form/blob/dev/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of DripForm、DripFormTheme.
- [ ] I have read the console error message carefully (if applicable).

### Description

<img width="1770" alt="image" src="https://user-images.githubusercontent.com/36527485/182995479-6231d070-607e-481c-ada5-da4b260f3b76.png">

### Steps to reproduce

1. form渲染组件
2. 控制台有 formMode warning提示

### Current behavior

/

### Expected behavior

/

### Your environment

- DripForm version used: 0.9.0-alpha.0
- DripFormTheme used: 0.9.0-alpha.0
- DripFormTheme version used: 0.9.0-alpha.0

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by mengshang918** [comment] 2022-08-12 09:17
Duplicate of #226

**Closed as completed by mengshang918** 2022-08-12 09:17 UTC
Labels: bug, duplicate
