### ISSUE TITLE
[Bug] 时间选择器和日期选择器，开启范围，设置默认时间/占位符不生效

### ISSUE THREAD

**Issue by Henry129999** [jd-opensource/drip-form#106] opened 2022-01-06 13:04 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/JDFED/drip-form/blob/dev/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of DripForm、DripFormTheme.
- [X] I have read the console error message carefully (if applicable).

### Description

时间选择器和日期选择器，开启范围，设置默认时间/占位符不生效

![image](https://user-images.githubusercontent.com/36527485/148387212-6a22af0e-b6ac-4ceb-b645-464c751a2285.png)

### Steps to reproduce

1. 时间选择器和日期选择器
2. 开启范围
3. 设置默认时间/占位符不生效

### Current behavior

设置默认时间/占位符不生效

### Expected behavior

设置默认时间/占位符生效

### Your environment

- DripForm version used: 
- DripFormTheme used:
- DripFormTheme version used:

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by mengshang918** [comment] 2022-01-12 08:35
Duplicate of #97

**Closed as completed by mengshang918** 2022-01-12 08:35 UTC
Labels: bug
